# Generated by Django 3.2.8 on 2021-10-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoalCPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KalimatSoal', models.CharField(default='', max_length=8)),
                ('GambarSoal', models.ImageField(upload_to='CPM/Soal')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanCPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KalimatJawaban', models.CharField(default='', max_length=8)),
                ('GambarJawaban', models.ImageField(upload_to='CPM/Jawaban')),
                ('KonektorJawaban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alat_test.soalcpm')),
            ],
        ),
    ]
